#!/bin/sh
npx eslint --max-warnings=0 src api/src || {
  echo "ESLint check failed. Commit aborted."
  exit 1
}

cd ./api && npx jest || {
  echo "Tests failed. Commit aborted."
  exit 1
}

cd .. && npx prettier --write .
git update-index --again